version: 1.0.{build}

install:
    - nuget restore

build:
  project: Keen.sln
  verbosity: detailed

environment:
    COVERALLS_REPO_TOKEN:  
       secure: 2nxO1JRH1PJLfBfqV4sAev9lGZ8afm6bq1wTGbgPw5w/FF+lmFghU2JZjTFz2wXd

after_test: 
# generate report for NUnit testing framework:
    - packages\OpenCover.4.5.3723\OpenCover.Console.exe -register:user -filter:"+[*]*" -target:"packages\NUnit.Runners.2.6.4\tools\nunit-console.exe" -targetargs:"/noshadow /domain:single  Keen.NET.Test\bin\Debug\Keen.Net.Test.dll" -output:coverage.xml
	
- packages\coveralls.io.1.3.4\tools\coveralls.net.exe --opencover coverage.xml

